string_pattern_type: legacy
text_extensions: [ 'haml', 'sass', 'erubis' ]
output_dir: output
data_sources:
  -
    type: filesystem_unified
    identifier_type: legacy
    items_root: /
    layouts_root: /
    encoding: utf-8
